import Link from "next/link"

const guides = [
    { number: "01", title: "How to make App Store screenshots", description: "A complete workflow for planning a screenshot sequence, writing benefit-led headlines, composing each frame, and exporting a store-ready set.", intent: "App Store screenshots", slug: "your-first-app-store-screenshot" },
    { number: "02", title: "App Store screenshot sizes & requirements", description: "Current Apple and Google Play dimensions, file rules, and upload checklist—kept as the quick reference page for launch day.", intent: "Screenshot sizes", slug: "app-store-screenshot-sizes" },
    { number: "03", title: "App Store screenshot design", description: "Use headline formulas, visual hierarchy, spacing, colour, and device framing to make screenshots understandable at a glance.", intent: "Screenshot design", slug: "text-overlays-and-branding" },
    { number: "04", title: "App Store screenshot examples", description: "Learn the design patterns behind clear screenshot sets and decide when flat UI or a device mockup best communicates the product.", intent: "Screenshot examples", slug: "3d-mockup-vs-flat-screenshot" },
    { number: "05", title: "App Store screenshots for subscription apps", description: "A six-frame narrative that sells the ongoing outcome first, supports it with proof, and introduces the offer without leading with a paywall.", intent: "Subscription app screenshots", slug: "app-store-screenshots-subscription-app" },
    { number: "06", title: "How to create an iPhone mockup from a screenshot", description: "Turn an app screen into a realistic iPhone mockup, then choose the right angle, lighting, background, and export for its destination.", intent: "iPhone mockup", slug: "create-iphone-mockup" },
    { number: "07", title: "How to create a MacBook mockup from a website screenshot", description: "Make polished desktop product visuals for SaaS websites, launch pages, portfolios, and pitch decks.", intent: "MacBook mockup", slug: "create-macbook-mockup" },
    { number: "08", title: "SaaS landing page mockups", description: "Plan the hero, feature, and supporting product visuals that make a software landing page easier to understand and trust.", intent: "SaaS landing page mockups", slug: "mockups-for-saas-landing-page" },
    { number: "09", title: "How to make an app promo video", description: "Storyboard and export a short product demo with clear opening frames, camera motion, screen recordings, and readable copy.", intent: "App promo video", slug: "make-app-promo-video" },
    { number: "10", title: "App Preview video requirements", description: "Build a compliant, conversion-focused App Store preview: what to show, how to keep it readable without sound, and the required technical format.", intent: "App Preview video", slug: "app-preview-video-app-store" },
]

export default function GuidesIndex() {
    return <main className="mx-auto max-w-4xl px-6 py-20">
        <div className="mb-16"><p className="mb-4 text-sm font-medium uppercase tracking-widest text-muted-foreground">Guides</p><h1 className="text-4xl font-bold tracking-tight md:text-5xl">App Store screenshots, mockups, and promo video guides</h1><p className="mt-4 max-w-2xl text-lg text-muted-foreground">Practical, screenshot-led walkthroughs for the launch assets people actually search for—from App Store screenshots to iPhone mockups and product demos.</p></div>
        <div className="space-y-4">{guides.map((guide) => <Link key={guide.slug} href={`/guides/${guide.slug}`} className="group block rounded-2xl border border-border/60 bg-secondary/20 p-6 transition-all hover:border-border hover:bg-secondary/40"><div className="flex items-start gap-4"><span className="w-12 shrink-0 text-3xl font-bold text-blue-500">{guide.number}</span><div className="min-w-0 flex-1"><p className="text-xs font-medium uppercase tracking-widest text-muted-foreground">{guide.intent}</p><h2 className="mt-1 text-xl font-semibold tracking-tight">{guide.title}</h2><p className="mt-2 text-muted-foreground">{guide.description}</p></div><span className="self-center text-lg text-muted-foreground/40 transition-colors group-hover:text-muted-foreground/70">&rarr;</span></div></Link>)}</div>
    </main>
}
